export const SET_CITIES = "SET_CITIES";
export const SET_COPYOF_CITIES = "SET_COPYOF_CITIES";

export const SET_DISTRICTS = "SET_DISTRICTS";

export const SET_SELECTED_DISTRICT = "SET_SELECTED_DISTRICT";
export const SET_COPY_SELECTED_DISTRICT = "SET_COPY_SELECTED_DISTRICT";
export const SET_EDITABLE_DISTRICT = "SET_EDITABLE_DISTRICT";
export const SET_EDITABLE_CITY = "SET_EDITABLE_CITY";
export const SET_CITY_MODAL_VISIBLE = "SET_CITY_MODAL_VISIBLE";
export const SET_DISTRICT_MODAL_VISIBLE = "SET_DISTRICT_MODAL_VISIBLE";
