export const SET_TAX_OFFICES = "SET_TAX_OFFICES";
export const SET_TAXOFFICE_MODAL_VISIBLE = "SET_TAXOFFICE_MODAL_VISIBLE";
export const SET_SELECTED_TAXOFFICES = "SET_SELECTED_TAXOFFICES";
export const SET_COPY_TAXOFFICES = "SET_COPY_TAXOFFICES";

export const SET_EDITABLE_TAXOFFICE = "SET_EDITABLE_TAXOFFICE";
