export const SET_SELLERS = "SET_SELLERS";
export const SET_SELLER_INFO = "SET_SELLER_INFO";
export const SET_SELLER_CONTACTS = "SET_SELLER_CONTACTS";
export const SET_SELLER_CONTACT_MODAL_VISIBLE =
  "SET_SELLER_CONTACT_MODAL_VISIBLE";
export const SET_SELLER_ADRESS = "SET_SELLER_ADRESS";
